registersDict = {
"MODEL_NUMBER" : [ 0 , 2 ] ,
"VERSION" : [ 2 , 1 ] ,
"ID" : [ 3 , 1 ] ,
"BAUD_RATE" : [ 4 , 1 ] ,
"RETURN_DELAY_TIME" : [ 5 , 1 ] ,
"CW_ANGLE_LIMIT" : [ 6 , 2 ] ,
"CCW_ANGLE_LIMIT" : [ 8 , 2 ] ,
"SYSTEM_DATA2" : [ 10 , 1 ] ,
"LIMIT_TEMPERATURE" : [ 11 , 1 ] ,
"DOWN_LIMIT_VOLTAGE" : [ 12 , 1 ] ,
"UP_LIMIT_VOLTAGE" : [ 13 , 1 ] ,
"RETURN_LEVEL" : [ 16 , 1 ] ,
"ALARM_LED" : [ 17 , 1 ] ,
"ALARM_SHUTDOWN" : [ 18 , 1 ] ,
"OPERATING_MODE" : [ 19 , 1 ] ,
"DOWN_CALIBRATION" : [ 20 , 2 ] ,
"UP_CALIBRATION" : [ 22 , 2 ] ,
"TORQUE_ENABLE" : [ 24 , 1 ] ,
"LED" : [ 25 , 1 ] ,
"CW_COMPLIANCE_MARGIN" : [ 26 , 1 ] ,
"CCW_COMPLIANCE_MARGIN" : [ 27 , 1 ] ,
"CW_COMPLIANCE_SLOPE" : [ 28 , 1 ] ,
"CCW_COMPLIANCE_SLOPE" : [ 29 , 1 ] ,
"GOAL_POSITION" : [ 30 , 2 ] ,
"GOAL_SPEED" : [ 32 , 2 ] ,
"TORQUE_LIMIT" : [ 34 , 2 ] ,
"PRESENT_POSITION" : [ 36 , 2 ] ,
"PRESENT_SPEED" : [ 38 , 2 ] ,
"PRESENT_LOAD" : [ 40 , 2 ] ,
"PRESENT_VOLTAGE" : [ 42 , 1 ] ,
"PRESENT_TEMPERATURE" : [ 43 , 1 ] ,
"REGISTERED_INSTRUCTION" : [ 44 , 1 ] ,
"PAUSE_TIME" : [ 45 , 1 ] ,
"MOVING" : [ 46 , 1 ] ,
"LOCK" : [ 47 , 1 ] ,
"PUNCH" : [ 48 , 2 ] 
}
